version: "3.9"
services:
  db:
    image: postgres:13.4
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=chesnok2002
      - POSTGRES_DB=DapperDb
      - PGDATA=/var/lib/postgresql/data/pgdata
    networks:
      - app-network
    ports:
      - "5432"
    volumes:
      - ./pgData:/var/lib/postgresql/data/pgdata
  server:
    build: .
    container_name: application
    ports:
      - "80:80"
    links:
      - db
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgData:
  